### ISSUE TITLE
Assignment 1 feedback

### ISSUE THREAD

**Issue by mauslerm** [core-interaction-lab/assignments-jessiekil#1]
Please use the below validator to find and fix all errors and warnings in your code. You can copy the code from your editor, paste into the text box on the site, and click the Check button to see your results. Adjust your code and continue using the validator until no errors remain.

- HTML validator (for .html files): [https://validator.w3.org/#validate_by_input](https://validator.w3.org/#validate_by_input) 

I've added some tips below

- You should move this code from the exercise-1 directory to the assignment-1 directory
- Different HTML elements are designated as "block" or "inline" elements ([read more here](https://www.w3schools.com/htmL/html_blocks.asp)). `span` elements are considered inline elements, so shouldn't be used to wrap block elements. You're wrapping all of your content on `index.html` and `main3.html` in a `span` tag, which will trigger an error in the validator. You can resolve this by changing the `span` tag to a `div`, or better yet a `section` tag.

**Comment by jessiekil** [comment]
Hi, Thank you!

https://core-interaction-lab.github.io/assignments-jessiekil/exercises/exercise-1/index.html

I edited the errors for my HTML pages.

**Comment by mauslerm** [comment]
Good work!
